# Generated by Django 4.2 on 2023-07-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
